// Mocks generated by Mockito 5.4.5 from annotations
// in spotify/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:spotify/core/failure/failure.dart' as _i5;
import 'package:spotify/data/dtos/auth/create_user_dto.dart' as _i6;
import 'package:spotify/data/models/auth/signin_user_req.dart' as _i7;
import 'package:spotify/domain/entities/auth/user_entity.dart' as _i8;
import 'package:spotify/domain/repository/auth/auth_repositoy.dart' as _i3;
import 'package:spotify/domain/usecases/auth/is_user_logged_in_usecase.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_1 extends _i1.SmartFake
    implements _i3.AuthRepository {
  _FakeAuthRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> signup(_i6.CreateUserDto? user) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [user]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#signup, [user]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<dynamic, dynamic>> sigin(_i7.SigninUserReq? user) =>
      (super.noSuchMethod(
            Invocation.method(#sigin, [user]),
            returnValue: _i4.Future<_i2.Either<dynamic, dynamic>>.value(
              _FakeEither_0<dynamic, dynamic>(
                this,
                Invocation.method(#sigin, [user]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<dynamic, dynamic>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i8.UserEntity>(
                    this,
                    Invocation.method(#getUser, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>>);

  @override
  bool isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [IsUserLoggedInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsUserLoggedInUseCase extends _i1.Mock
    implements _i9.IsUserLoggedInUseCase {
  MockIsUserLoggedInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_1(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i3.AuthRepository);

  @override
  _i4.Future<bool> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
