// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRETW2SaBCkZTeEao04RQiMXVuYIB-Iso',
    appId: '1:288983927760:web:f471da61df8374d20587d5',
    messagingSenderId: '288983927760',
    projectId: 'spotify-harc99',
    authDomain: 'spotify-harc99.firebaseapp.com',
    storageBucket: 'spotify-harc99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7w9NNbhVOypg6dc_amU0895QU4aS9I5M',
    appId: '1:288983927760:android:2f98ac9e084daa970587d5',
    messagingSenderId: '288983927760',
    projectId: 'spotify-harc99',
    storageBucket: 'spotify-harc99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq5b457N2OriF9IYYahs85sq_zrJiWjeI',
    appId: '1:288983927760:ios:43da6fcfcfd9c37e0587d5',
    messagingSenderId: '288983927760',
    projectId: 'spotify-harc99',
    storageBucket: 'spotify-harc99.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq5b457N2OriF9IYYahs85sq_zrJiWjeI',
    appId: '1:288983927760:ios:43da6fcfcfd9c37e0587d5',
    messagingSenderId: '288983927760',
    projectId: 'spotify-harc99',
    storageBucket: 'spotify-harc99.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRETW2SaBCkZTeEao04RQiMXVuYIB-Iso',
    appId: '1:288983927760:web:c7af1dedf0b7b3060587d5',
    messagingSenderId: '288983927760',
    projectId: 'spotify-harc99',
    authDomain: 'spotify-harc99.firebaseapp.com',
    storageBucket: 'spotify-harc99.firebasestorage.app',
  );
}
