// Mocks generated by Mockito 5.4.5 from annotations
// in spotify/test/app/common/bloc/favorite_button/favorite_button_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:spotify/domain/repository/song/song_repository.dart' as _i2;
import 'package:spotify/domain/usecases/song/add_or_remove_favorite_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSongRepository_0 extends _i1.SmartFake
    implements _i2.SongRepository {
  _FakeSongRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AddOrRemoveFavoriteUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddOrRemoveFavoriteUsecase extends _i1.Mock
    implements _i4.AddOrRemoveFavoriteUsecase {
  MockAddOrRemoveFavoriteUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SongRepository get songRepository =>
      (super.noSuchMethod(
            Invocation.getter(#songRepository),
            returnValue: _FakeSongRepository_0(
              this,
              Invocation.getter(#songRepository),
            ),
          )
          as _i2.SongRepository);

  @override
  _i5.Future<_i3.Either<dynamic, dynamic>> call(String? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<dynamic, dynamic>>.value(
              _FakeEither_1<dynamic, dynamic>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<dynamic, dynamic>>);
}
