// Mocks generated by Mockito 5.4.5 from annotations
// in spotify/test/app/data/repository/auth/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:spotify/core/failure/failure.dart' as _i5;
import 'package:spotify/data/dtos/auth/create_user_dto.dart' as _i6;
import 'package:spotify/data/models/auth/signin_user_req.dart' as _i7;
import 'package:spotify/data/models/auth/user_model.dart' as _i8;
import 'package:spotify/data/sources/auth/auth_firebase_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthFirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthFirebaseService extends _i1.Mock
    implements _i3.AuthFirebaseService {
  MockAuthFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> signup(_i6.CreateUserDto? user) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [user]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#signup, [user]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> signin(_i7.SigninUserReq? user) =>
      (super.noSuchMethod(
            Invocation.method(#signin, [user]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#signin, [user]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.UserModel>> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.UserModel>>.value(
                  _FakeEither_0<_i5.Failure, _i8.UserModel>(
                    this,
                    Invocation.method(#getUser, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.UserModel>>);

  @override
  bool isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: false,
          )
          as bool);
}
